### ISSUE TITLE
Cant compile due to Floats_array.h

### ISSUE THREAD

**Issue by inaciose** [bandasaikrishna/ros_control_example#1]
error message on catkin_make
ros_control_example/include/ros_control_example/robot_hardware_interface.h:12:10: fatal error: three_dof_planar_manipulator/Floats_array.h: No such file or directory

I also cloned the three_dof_planar_manipulator, and after catkin_make I found the Floats_array.h devel folder. But still does not compile with same message

**Comment by inaciose** [comment]
Found a solution. Just add /home/user/catkin_ws/devel/include/ to the include directories in CMakeLists.txt

include_directories(
 include
  ${catkin_INCLUDE_DIRS}
 include
  /home/user/catkin_ws/devel/include/
)

**Comment by civcode** [comment]
Had the same problem. Cloned "3-DOF_Manipulator" and copied the folder "three_dof_planar_manipulator" to catkin_ws/src/.

The build error can be fixed by configuring the correct build oder of the packages (three_dof_planar_manipulator has to be built first because it generates Floats_array.h).

In "src/ros_control_example/CMakeLists.txt" uncomment line 157:
add_dependencies(robot_hardware_interface ${catkin_EXPORTED_TARGETS})
